### ISSUE TITLE
support voryx/Thruway with reactphp/event-loop's libevent backend

### ISSUE THREAD

**Issue by geki-yaba** [expressif/pecl-event-libevent#8] opened 2016-02-01 17:58 UTC
To make thruway[2] WAMPv2 router not crash starting and stopping event loop[3] I have to apply a patch[0]. The changes I made are based on php-ext-interbase[1] git.

Though, I do not know if this is the completely right way to fix. Any help is welcome.

[0] https://github.com/geki-yaba/gekis-playground/blob/master/dev-php/pecl-libevent/files/libevent.c.patch
[1] http://git.php.net/?p=php-src.git;a=blob_plain;f=ext/interbase/ibase_events.c;hb=HEAD
[2] https://github.com/voryx/Thruway
[3] https://github.com/reactphp/event-loop

**Comment by geki-yaba** [comment] 2016-02-01 22:05
JFYI, corrected and simplified patch.

**Comment by ichiriac** [comment] 2016-02-01 23:42
Hi Geki,

Please fork this repo and make a pull request :
https://help.github.com/articles/fork-a-repo/

To be sure that this bug will not occur for the next releases also add a test that reproduce the bug like this one :
https://github.com/expressif/pecl-event-libevent/blob/master/tests/libevent003.phpt

Thanks for helping :+1:

**Comment by ichiriac** [comment] 2016-04-08 19:56
Hi @geki-yaba,

You patch is just hiding the error and it's introducing a new memory leak. I've fixed the bug, you should try with the new code.

Thanks again for your help and pointing out this problem.

**Comment by geki-yaba** [comment] 2016-04-09 06:36
Surely it was not perfect. I know zero about PHP Zend/C coding. :-)

Though, it adjusted the reference count, which was zero leaving the initialization of a new event instance, leading to destruction of that event instance before use in PHP and results in a segmentation fault.

Well, just a user pov of this issue. And sorry, that I got no time for a proper patchset with test.
Like you see my patch was just to demonstrate, not to fix. ;-)

I will check now, if it works.

**Comment by geki-yaba** [comment] 2016-04-09 06:51
HEAD causes segmentation fault.

**Comment by geki-yaba** [comment] 2016-04-09 07:17
https://github.com/expressif/pecl-event-libevent/commit/6887d83fcb315d5dfb6d27e92bc2e979bea69169

-> crashes on termination

https://github.com/expressif/pecl-event-libevent/commit/ac255b86138de94d53388487e52d87fa9b92e278

-> removed reference count again; crashes on initialization

**Comment by ichiriac** [comment] 2016-04-09 07:47
could you please provide a little php code that reproduce the behaviour

**Comment by geki-yaba** [comment] 2016-04-09 10:25
Tried to strip ratchet's libevent down to a testcase. No luck. I do not quite get what they do differently.

**Comment by ichiriac** [comment] 2016-04-09 10:59
got a ref count problem on https://github.com/expressif/pecl-event-libevent/blob/master/libevent.c#L508 - at the first incoming connection ...

**Comment by geki-yaba** [comment] 2016-04-09 11:40
A ha, doing procedural calls, it is just fine.
Wrap libevent code into PHP classes, things get buggy with former HEAD.

$ cat /tmp/libevent-6887d83fcb315d5dfb6d27e92bc2e979bea69169.txt 

# php bin/libevent-test.php

about to start in a sec ...
.x...x...x..^C..PHP Warning:  Unknown list entry type (0) in
/usr/local/src/BookPublisher/bin/libevent-test.php on line 77
xSegmentation fault

Although, with current HEAD it does not segfault. I am missing one piece.
Maybe the server connection setup or such

**Comment by ichiriac** [comment] 2016-04-09 14:05
I've tested with a class wrapper and it works. I've also reproduced the bug with thruway - it looks like the base->rsrc_id is no more referenced when calling event_base_set function at socket_accept.

 I need a simple code to be able to reproduce the bug and figure out the reasons of the fail ...

**Comment by geki-yaba** [comment] 2016-04-10 09:24
My current testcase is here:
http://geki.selfhost.eu/hacks/libevent-test.phps

Results with latest commits:
3784a2b0c52e20d3d4314dccee45c6f7604d22d0 -> no crash, exit ok (after ctrl+c) but PHP Warning: event_add(): supplied resource is not a valid event resource in libevent-test.php on line 49
6887d83fcb315d5dfb6d27e92bc2e979bea69169 -> crash on exit (after ctrl+c) and PHP Warning: Unknown list entry type (0) in libevent-test.php on line 110
ac255b86138de94d53388487e52d87fa9b92e278 -> crash on exit (after ctrl+c)
9e72744ce6224beafc7b54ce2a3a990f1c552a5a -> crash on exit (after ctrl+c)

**Comment by geki-yaba** [comment] 2016-04-10 09:37
Well, just to note, thruway crashes here on start while entering the actual event loop not like my testcase above on exit.

Luckily I can post my thruway server code here:
http://geki.selfhost.eu/hacks/thru-server.phps

**Comment by ichiriac** [comment] 2017-03-09 08:49
Hi @geki-yaba,

Thanks for your help, and sorry for the late reply. I start again to work on this migration. 

I'll take a look at your snippets this weekend.

**Comment by ichiriac** [comment] 2017-03-09 21:47
Hi @geki-yaba,

Not sure, but maybe the bug was related to https://github.com/expressif/pecl-event-libevent/issues/14.

I've made some changes, could you try and tell me if you can reproduce the error ?

**Comment by geki-yaba** [comment] 2017-03-10 17:23
Sadly, I moved to pecl-event backend, which works with voryx/Thruway on php7.

But IIRC, voryx/Thruway uses event_timer_new. O well, maybe not. Sorry, that I cannot help anymore.

**Comment by ichiriac** [comment] 2017-03-10 17:50
Great news, anyway, libevent2 is a dead project from years, so this binding is only for migrating legacy code. 

I'm glad you have migrated on a stable and actively maintained version. I will close this issue as I can't myself reproduce the error anymore.

**Closed as completed by ichiriac** 2017-03-10 17:50 UTC
Labels: bug
