### ISSUE TITLE
supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by sm2017** [expressif/pecl-event-libevent#11] opened 2017-01-09 07:32 UTC
See https://github.com/walkor/Workerman/issues/130

**Comment by sm2017** [comment] 2017-02-12 07:39
Reply please , I open this Issue on Jan 9 and I need to solve the problem , Help please

Please see https://github.com/walkor/Workerman/issues/130

I test it in php5.6 and libevent , it works well but in php7 and libevent , I have this error

```
PHP Warning:  stream_set_blocking(): supplied resource is not a valid stream resource in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 263

Warning: stream_set_blocking(): supplied resource is not a valid stream resource in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 263
PHP Warning:  stream_set_read_buffer(): supplied resource is not a valid stream resource in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 266

Warning: stream_set_read_buffer(): supplied resource is not a valid stream resource in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 266
PHP Warning:  socket_import_stream(): supplied resource is not a valid stream resource in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 270

Warning: socket_import_stream(): supplied resource is not a valid stream resource in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 270
PHP Warning:  socket_set_option() expects parameter 1 to be resource, boolean given in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 271

Warning: socket_set_option() expects parameter 1 to be resource, boolean given in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 271
PHP Warning:  socket_set_option() expects parameter 1 to be resource, boolean given in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 272

Warning: socket_set_option() expects parameter 1 to be resource, boolean given in /home/app/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 272
PHP Warning:  event_set(): fd argument must be either valid PHP stream or valid PHP socket resource in /home/app/vendor/workerman/workerman/Events/Libevent.php on line 105

Warning: event_set(): fd argument must be either valid PHP stream or valid PHP socket resource in /home/app/vendor/workerman/workerman/Events/Libevent.php on line 105
PHP Warning:  event_set(): fd argument must be either valid PHP stream or valid PHP socket resource in /home/app/vendor/workerman/workerman/Events/Libevent.php on line 105

Warning: event_set(): fd argument must be either valid PHP stream or valid PHP socket resource in /home/app/vendor/workerman/workerman/Events/Libevent.php on line 105

```

**Comment by sm2017** [comment] 2017-02-12 07:40
@ichiriac Help me

**Comment by ichiriac** [comment] 2017-02-12 16:56
Hi @sm2017,

Sorry, I've not saw your issue before today.  I think the problem comes with this statement :
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L261

Running this statement :
https://github.com/walkor/Workerman/blob/master/Events/Libevent.php#L127

This will run into the code (and it's okay) :
https://github.com/expressif/pecl-event-libevent/blob/master/libevent.c#L771

Not sure why (bad refcount maybe), but also seems to trigger this code :
https://github.com/expressif/pecl-event-libevent/blob/master/libevent.c#L153

I need to check this in debug mode but for me, when you call the del function, followed by event_del statement, it seems that the object after unset does not have any more references to him. The garbage collector passes, and kills the object (line 153 on libevent.c), and the ressource is also closed. 

After investigations, this line is changes to be compliant with PHP7 (zend_list_delete to zend_list_close) 

> In most user extension functions like mysql_close(), you should use zend_list_close() instead of zend_list_delete(). This closes the actual connection and frees extension specific data structures, but doesn't free the zend_reference structure. that might be still referenced from zval(s). This also doesn't decrement the resource reference counter.

So when the event is destroyed (no more references to him), the connection is closed, that explains your warnings.

One solution could be to revert back to `zend_list_delete` but I believe that makes memory leaks (not sure).

---

Sorry but I have no time to work again on libevent, maybe in few month I will be back again on this but for now I'm stuck on other projects.

> If you know C fork me and make a pull request, I'll check it and package it for windows libraries.

**Comment by sm2017** [comment] 2017-02-19 08:17
@ichiriac ,  I need to fix the bug , Please fix it ASAP and help me 
Thanks

**Comment by ichiriac** [comment] 2017-02-19 09:09
ok @sm2017, ping me back in 1 month if it's not moving. I'll update this issue when it will be fixed.

**Comment by sm2017** [comment] 2017-02-20 07:56
Thanks a lot , I will check this page periodically 
Thanks again 👍

**Comment by forkeer** [comment] 2017-02-20 08:11
@ichiriac i have this issue too but i forget that if you solve its nice help for me

**Comment by sm2017** [comment] 2017-03-08 05:44
@ichiriac Update me please

**Comment by ichiriac** [comment] 2017-03-08 10:23
Hi @sm2017,

I'll take a look at this tonight

**Comment by sm2017** [comment] 2017-03-08 17:50
Thanks a lot 😆 👍

**Comment by ichiriac** [comment] 2017-03-09 00:08
I'll continue tomorrow, I've did not succeed to force the GC with a small code

**Comment by sm2017** [comment] 2017-03-09 06:05
I hope , the following references helps

## stream_socket_client - STREAM_CLIENT_ASYNC_CONNECT
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L171-L172

## EV_WRITE
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L186

## supplied resource is not a valid stream resource
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L263
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L266
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L270
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L271-L272

## fd argument must be either valid PHP stream or valid PHP socket resource
https://github.com/walkor/Workerman/blob/master//Events/Libevent.php#L105

**Comment by ichiriac** [comment] 2017-03-09 21:42
Hi @sm2017,

The issue should be fixed, can you try by rebuilding from sources or do you need windows binaries ?

I can't reproduce the bug directly as in PHP7 it's not easy to trigger the GC, so I need you to test and tell me if it's OK.

Then I'll take tome time to find out a way to trigger properly the garbage collector, in order to cover this ticket with tests

**Comment by sm2017** [comment] 2017-03-11 06:07
I install libevent @05900f3b8d70deb424b3193a4eb850062f146638 ,  but same result , I have ``` supplied resource is not a valid stream resource``` error

Read http://php.net/manual/en/function.gc-collect-cycles.php maybe helps

**Comment by sm2017** [comment] 2017-03-12 08:46
See https://github.com/expressif/pecl-event-libevent/pull/16 I found that the problem is ```event_free``` that called at https://github.com/reactphp/event-loop/blob/master/src/LibEventLoop.php#L103

Before event_free the $fd is resource of type (stream) and after resource of type (Unknown) so in next lines we have ```supplied resource is not a valid stream resource``` error

**Comment by ichiriac** [comment] 2017-03-12 08:49
ouch : https://github.com/expressif/pecl-event-libevent/blob/master/libevent.c#L605 - explicitely closes the list / was not the case before the migration : https://github.com/php/pecl-event-libevent/blob/master/libevent.c#L605

**Comment by sm2017** [comment] 2017-03-12 08:59
I install again libevent extension and run test script the result is 

```php
<?php

/* poll STDIN using basic API */
function foo($fd, $events, $arg)
{
    static $i;

    $i++;

    if ($i == 10) {
        event_base_loopexit($arg[1]);
    }
    var_dump(fread($fd, 1));
}


$base = event_base_new();

$fd = fopen('https://raw.githubusercontent.com/expressif/pecl-event-libevent/master/tests/input.txt', 'r');

// first event reader
$ev1 = event_new();
var_dump(event_set($ev1, $fd, EV_READ | EV_PERSIST, "foo", array($ev1, $base)));
var_dump(event_base_set($ev1, $base));
var_dump(event_add($ev1));
var_dump(event_base_loop($base, EVLOOP_ONCE));
var_dump(event_del($ev1));
var_dump($fd);
event_free($ev1);
unset($ev1);
var_dump($fd);

// second event reader
$ev2 = event_new();
var_dump(event_set($ev2, $fd, EV_READ | EV_PERSIST, "foo", array($ev2, $base)));
var_dump(event_base_set($ev2, $base));
var_dump(event_add($ev2));
var_dump(event_base_loop($base, EVLOOP_ONCE));
var_dump(event_del($ev2));
unset($ev2);

?>

```

```
bool(true)
bool(true)
bool(true)
string(1) "0"
int(0)
bool(true)
resource(6) of type (stream)
resource(6) of type (Unknown)
PHP Warning:  event_set(): fd argument must be either valid PHP stream or valid PHP socket resource in /home/libeventBug/test.php on line 35
bool(false)
bool(false)
PHP Warning:  event_add(): Unable to add event without an event base in /home/libeventBug/test.php on line 37
bool(false)
int(1)
PHP Warning:  event_del(): Unable to delete event without an event base in /home/libeventBug/test.php on line 39
bool(false)
[warn] event_del: event has no event_base set.

```

**Comment by ichiriac** [comment] 2017-03-12 09:13
@sm2017, I'm looking at it, I'll tell you when it's fixed so you can test

**Comment by sm2017** [comment] 2017-03-12 09:17
@ichiriac Ok just I found another issue 

See https://github.com/walkor/Workerman/blob/master/Events/Libevent.php#L84 , the 2th argument of ```event_set``` is 0 that is integer not resource , I see http://php.net/manual/en/function.event-set.php and 2th argument is mixed and Signal number or resource indicating the stream.  but with expressif/pecl-event-libevent we have this error ```PHP Warning:  event_set(): invalid file descriptor passed ```

**Comment by ichiriac** [comment] 2017-03-12 09:55
@sm2017, this bug is now fixed, travis passed, waiting your confirmation.

For the other bug can you open a new issue and send a PR with a phpt to reproduce the error, check the output with php5 in order to get the output for the expected section.

**Comment by sm2017** [comment] 2017-03-12 10:07
I run test script and it works , but in main project I have issue let me find the problem

**Comment by sm2017** [comment] 2017-03-12 10:47
I think we have ```Segmentation fault``` in new commit

In this line https://github.com/walkor/Workerman/blob/152756a04f95645217d159f5a496077de0be65cd/Worker.php#L1022 we have ```pcntl_wait``` after I install libevent ```$status``` is SIGSEGV = 11

**Comment by sm2017** [comment] 2017-03-13 09:34
I want to create a phpt file for Segmentation fault bug , But I cannot , Can you help me?

I know the problem is ```event_add``` but cannot reproduce error

Please do following
```
git clone https://github.com/walkor/workerman-chat
cd workerman-chat
composer install
php start.php start
```

The code running in following order 

https://github.com/walkor/GatewayWorker/blob/master/src/Gateway.php#L819
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L171
https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L186
https://github.com/walkor/Workerman/blob/master/Events/Libevent.php#L113


The problem is https://github.com/walkor/Workerman/blob/master/Events/Libevent.php#L113 I don't know why in this line script will be terminated and send SIGSEGV to parent process

https://github.com/walkor/Workerman/blob/master/Worker.php#L1022

But in PHP 5.6 and libevent it workes well

**Comment by ichiriac** [comment] 2017-03-24 13:51
Hi @sm2017,

This is another issue, we can continue here : https://github.com/expressif/pecl-event-libevent/issues/19

I will close this one as it's fixed.

**Closed as completed by ichiriac** 2017-03-24 13:51 UTC
Labels: bug
